version: 1
id: build
name: build
servers:
- type: image
  secrets: default
  image: mcp/filesystem@sha256:35fcf0217ca0d5bf7b0a5bd68fb3b89e08174676c0e0b4f431604512cf7b3f67
  snapshot:
    server:
      name: ts-fs-rw
      type: server
      image: mcp/filesystem@sha256:35fcf0217ca0d5bf7b0a5bd68fb3b89e08174676c0e0b4f431604512cf7b3f67
      description: Project filesystem rw
      title: ts-fs-rw
      remote: {}
      command:
      - /workspace
      volumes:
      - __WORKSPACE__:/workspace:rw
      disableNetwork: true
secrets:
  default:
    provider: docker-desktop-store
